### ISSUE TITLE
Random observations

### ISSUE THREAD

**Issue by Sim4n6** [Revel109/django-multiupload-lts#1]
Following your email on django-users group, here is some random observations : 

- _photos_ is not the right name for the app, but it is ok :)
- templates are pretty nice 
- Procfile logs nothing 
- DEBUG mode is ON
- secret_key is shared on the github repository.
- why are u using sqlite3 on heroku, it is gonna be reinitialized daily
- why not use Pipfile with pipenv tool, it is the recommended way lastly ... rather then a requirements.txt
- requirements.txt fix django version to 2.0 why not try it on 2.2 ?

could u please answer each one of the observations/questions ? thank u in advance.

**Comment by abu-yusuf-dev** [comment]
Thanks for the observation:

- Will change the name later
- Thanks
- Procfile for heroku deploy
- Changing it to OFF
- What is your suggestion here?
- I have a number of apps in heroku. I didn't find anything like this.
- I don't use pipenv
- I did try with all the versions from 2.0 ~ 2.2, working fine.

**Comment by Sim4n6** [comment]
For secret key uso os. Env get and store the value in heroku

**Comment by Sim4n6** [comment]
For Sqlite3 readthis plz https://devcenter.heroku.com/articles/sqlite3#disk-backed-storage
